### ISSUE TITLE
Color per rule, step?

### ISSUE THREAD

**Issue by poetaster** [anvaka/lsystem#11]
Hi. Nice tool! I wanted to suggest Color per step. Something like the mechanism here, http://www.kevs3d.co.uk/dev/lsystems/ In this case you can specify a color constant like this:

F=C0FF-[C1-F+F+F]+[C2+F-F-F] 

And that get's you closer to drawing actual plants :)

I'm going to build a wrapper Qt app for mobile phones based on your code and see what might be optimized for mobile. 
Thanks for nice system!

**Comment by anvaka** [comment]
I assume this should be possible.

Need to update gramar here https://github.com/anvaka/lsystem/blob/5e5d26188efae7b2a1d728aeb53dc217e8fe4e7e/src/LSystem.js#L80 and set proper color here https://github.com/anvaka/lsystem/blob/5e5d26188efae7b2a1d728aeb53dc217e8fe4e7e/src/Turtle.js#L56 in case if someone wants to try this

**Comment by poetaster** [comment]
Thanks for the tips! I'll see if I can get it working.

**Comment by poetaster** [comment]
Hmmm. I tried building with node/npm but it no longer builds with a lot of deprecated packages and dies on :

```npm ERR! prepareGitDep ./src/index.js → dist/gl-matrix-min.js...
npm ERR! prepareGitDep created dist/gl-matrix-min.js in 5.2s
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 2
npm ERR! prepareGitDep npm ERR! gl-matrix@3.3.0 build-dts: `tsc --allowJs --declaration --emitDeclarationOnly --module amd --outFile ./dist/index.d.ts ./src/index.js ./src/types.d.ts && node ./utils/bundle-dts.js && tsc --noEmit ./dist/index.d.ts`
```

I've hacked it into the the output:
```
 350                         {
 351                             key: "drawn",
 352                             value: function (e,f) {
 353                                 var t = this.position,
 354                                     r = this.direction,
 355                                     n = t[0] + e * r[0],
 356                                     i = t[1] + e * r[1],
 357                                     o = t[2] + e * r[2];
 358                                 this.lines.add({ from: t, to: [n, i, o], color: f }), (t[0] = n), (t[1] = i), (t[2] = o), this.scene.renderFrame();
 359                             },
 360                         },


 530                     { F: { name: "draw", args: [] }, f: { name: "move", args: [] }, "+": { name: "rotate", args: [n] }, "-": { name: "rotate", args: [-n] }, "[": { name: "push", args: [     ] }, "]": { name: "pop", args: [] },  C: { name: "color", args: [6553855] } },


 569             if ("color" === e.name) {
 570                 var m = x(e.args[0], "color");
 571                 console.log(n);
 572                 return function () {
 573                     t.turtle.drawn(10,m);
 574                 };
 575             }

```

Which is so wrong :)

**Comment by anvaka** [comment]
Ah, seem to be an old dependency issue. I've updated them just now - please try again installing with `npm i`

**Comment by poetaster** [comment]
I made a merge request: take a look at the following to get an idea of what I'm after.
```
// Tree
axiom: X
rules: 
 F => FF
 X => F-[[X]+X]+cF[+dFX]-X

color:brown
direction: [0, 1, 0]
angle: 22.5a
actions:
  c => chcolor(26)
  d => chcolor(83)
```

**Comment by anvaka** [comment]
Thank you for your contribution! This is now merged and deployed.

I have also [slightly changed](https://github.com/anvaka/lsystem/commit/953d6620c793e4eb8c7460cfc2a938c3493594c4) the parser and added synonym function name `setColor` to be more explicit. Here is how you can do it ([demo](https://anvaka.github.io/lsystem/?code=axiom%3A%20X%0Arules%3A%20%0A%20F%20%3D%3E%20FF%0A%20X%20%3D%3E%20F-%5B%5BX%5D%2BX%5D%2BcF%5B%2BdFX%5D-X%0A%0Acolor%3Abrown%0Adirection%3A%20%5B0%2C%201%2C%200%5D%0Aangle%3A%2022.5%0Aactions%3A%0A%20%20c%20%3D%3E%20setColor%28%27orange%27%29%0A%20%20d%20%3D%3E%20setColor%28%27%23F03571%27%29)):


```
axiom: X
rules: 
 F => FF
 X => F-[[X]+X]+cF[+dFX]-X

color: brown
direction: [0, 1, 0]
angle: 22.5
actions:
  c => setColor('orange')
  d => setColor('#F03571')
```

**Comment by poetaster** [comment]
> I have also [slightly changed](https://github.com/anvaka/lsystem/commit/953d6620c793e4eb8c7460cfc2a938c3493594c4) the parser and added synonym function name `setColor`

Thank you! I was being hesitant to turn to the parser, but this is obviously a more usable solution. Your naming is also generally more expressive. Thanks!
