### ISSUE TITLE
Swap the meaning of + and - 

### ISSUE THREAD

**Issue by tsakal** [anvaka/lsystem#2]
Hello anvaka.

In http://paulbourke.net/fractals/lsys/ we have the action : "&	         Swap the meaning of + and -".

Does this action implimented here;

Thank you.
Evangelos

**Comment by tsakal** [comment]
Maybe the solution is 

  let defaultRotationAngleSign = 1;
  let mergedActions = {
    'F': {name: 'draw', args: []},
    'f': {name: 'move', args: []},
    '+': {name: 'rotate', args: [defaultRotationAngle * defaultRotationAngleSign]},
    '-': {name: 'rotate', args: [-defaultRotationAngle * defaultRotationAngleSign]},
    '[': {name: 'push', args: []},
    ']': {name: 'pop', args: []},
    '&': {name: 'invert', args: [defaultRotationAngleSign = -defaultRotationAngleSign]},
    ...systemSettings.actions
  }
but i cant compile your code.

The goal is y-axis symmetry of an l-system graph.

**Comment by anvaka** [comment]
Got this implemented here: https://github.com/anvaka/lsystem/commit/eb447c632b640874f612c77bd02643965ec48dba

Thank you for the suggestion!
